export const SELECT_TAB = "SELECT_TAB";

export const SET_NAV = "SET_NAV";

export const HIDE_DOWNLOAD_APP_BANNER = "HIDE_DOWNLOAD_APP_BANNER";

export const ADD_SEARCH_HISTORY = "ADD_SEARCH_HISTORY";
